Feat/student class crud
pedrohrodrig/cp-presenca-cursinho-backend pull request #11
Opened 2024-09-30 23:08 UTC by VictorASantana

Eu percebi que tinha ficado umas coisas da studentClass que eu não tinha subido sabe-se lá porque, to subindo, mas vale olhar se ainda faz sentido. 
- Ajustes no modelo da studentClass
- Criação do endpoint de lesson para mobile

2024-10-01 01:11 UTC, pedrohrodrig approved these changes

2024-10-10 20:51 UTC, pedrohrodrig approved these changes

2024-10-10 20:51 UTC, pedrohrodrig commented on backend/attendance/migrations/0006_studentclass_modality_alter_studentclass_course.py
> +        ("attendance", "0005_alter_student_student_class"),
Eu comentei contigo há um tempo atrás, mas precisa mudar só o número da migration que faz referência (so puxar da develop e tu vai ver que tem outras migrations 0006 e 0007)

Aí tu muda essa linha pra coincidir com o nome do arquivo

Depois que alterar, pra testar é bom dar um `migrate attendance 0005` pra desfazer suas migrations e dps o migrate de novo pra aplicar as migrations na ordem certa

2024-10-10 20:51 UTC, pedrohrodrig commented on backend/attendance/migrations/0007_studentclass_end_datetime_and_more.py
> +        ("attendance", "0006_studentclass_modality_alter_studentclass_course"),
Aqui também, mas acho que no seu caso seria só mudar aqui pra 0008

2024-10-10 20:51 UTC, pedrohrodrig commented on backend/attendance/views.py
> +        queryset = Lesson.objects.all()
Não precisa declarar o queryset aqui se ele for igual ao que tá na classe (linha 23)

2024-10-11 10:47 UTC, lucas-pvg requested changes
N dá merge ainda n pq vai dar conflito

2024-10-14 12:35 UTC, closed without merging